import type { ServiceQuote } from "./domain";

export const quotes: ServiceQuote[] = [
  {
    provider: "OEM Precision",
    providerType: "Manufacturer service",
    status: "quote",
    packageTotal: 3100,
    callout: { amount: 350, inclusion: "additional" },
    calibration: { amount: 0, inclusion: "included" },
    parts: { amount: 500, inclusion: "additional" },
    responseHours: 18,
    turnaroundHours: 28,
    warrantyDays: 180,
    loanerIncluded: true,
    scopeMatch: 100,
    unknowns: [],
    evidence: [{ id: "oem-1", at: "02:14", quote: "That includes calibration and a six-month warranty." }],
  },
  {
    provider: "RapidBench",
    providerType: "Independent repair",
    status: "quote",
    packageTotal: 2450,
    callout: { amount: 450, inclusion: "additional" },
    calibration: { amount: 600, inclusion: "additional" },
    parts: { amount: 400, inclusion: "additional" },
    responseHours: 36,
    turnaroundHours: 52,
    warrantyDays: 90,
    loanerIncluded: false,
    scopeMatch: 86,
    unknowns: ["loaner"],
    evidence: [{ id: "rapid-1", at: "01:48", quote: "Calibration would be another six hundred dollars." }],
  },
  {
    provider: "MetroLab Field",
    providerType: "Regional service",
    status: "callback",
    packageTotal: 2800,
    callout: { amount: null, inclusion: "unknown" },
    calibration: { amount: 250, inclusion: "additional" },
    parts: { amount: 550, inclusion: "additional" },
    responseHours: 24,
    turnaroundHours: 40,
    warrantyDays: null,
    loanerIncluded: null,
    scopeMatch: 71,
    unknowns: ["callout fee", "warranty", "loaner"],
    evidence: [{ id: "metro-1", at: "03:08", quote: "I need our field manager to confirm warranty and call-out fees." }],
  },
];

export const concessions = [
  { at: "03:02", label: "Leverage verified", detail: "OEM offer includes calibration and a 24-hour response." },
  { at: "03:26", label: "Response improved", detail: "RapidBench moved from 48 hours to 36 hours." },
  { at: "03:55", label: "Warranty added", detail: "RapidBench added a 90-day labor warranty." },
  { at: "04:18", label: "Call-out reduced", detail: "Call-out fee changed from $650 to $450." },
];
